### ISSUE TITLE
MongoDB feature in liberty is going away - need to stop using it

### ISSUE THREAD

**Issue by rickettmwork** [WASdev/tool.lars#176]
This blog post has instructions on what needs to change:
https://openliberty.io/blog/2019/02/19/mongodb-with-open-liberty.html

**Comment by SteveFreeman** [comment]
Totally agree with this.  Also, these older MongoDB versions that the current driver can use does not include the latest, supported releases.  I believe this needs to be fixed _before_ the old MongoDB versions go out of support.

**Comment by tkburroughs** [comment]
To be clear, my understanding is that the old MongoDB versions are already out of support.
The driver used by the mongodb-2.0 feature is also already out of support.
The liberty mongodb-2.0 feature has been stabilized; and will never be enhanced. It will remain in Liberty indefinitely, and allow you to continue to use the unsupported driver and MongoDB version as long as they remain functional.

**Comment by SteveFreeman** [comment]
To be completely honest, you are mostly correct.  However, in our corporate environment, we must use supported software (not just functional software).  So in that respect I have to disagree with your conclusion.

I would like to see this implemented sooner rather than later.

**Comment by tkburroughs** [comment]
Per this website, Mongo 2.x has been "End of Life" and out of support since October 2016.  It is not an IBM product, not something we can change the support statement for. 

https://www.mongodb.com/support-policy

**Comment by SteveFreeman** [comment]
What's the support statement for updating LARS to support newer MongoDB versions (4.x)?

**Comment by tkburroughs** [comment]
Sorry if I've confused the issue a bit.  I was addressing support of MongoDB 2.x and associated drivers, and not referring to support of LARS.

A better title for this issue would be :

"mongodb-2.0 feature in liberty is stabilized - need to stop using it"

The "mongodb-2.0" feature is not "going away", nor has it been deprecated, just stabilized.  As far as I'm aware, no feature has ever been removed from liberty.  There are no plans to actually remove the mongodb-2.0 feature.  mongodb-2.0 provides the integration of the MongoDB 2.x drivers, and that integration is still supported, just stabilized, so it won't be enhanced or upgraded. Newer versions of MongoDB are already supported with liberty as described in the blog post above.

LARS is still fully supported, and this issue is to address moving it off the stabilized mongodb-2.0 feature to use something newer. I agree that it would be nice to have this done sooner rather than later to avoid any potential support complexities with using an older level of MongoDB.

**Comment by rickettmwork** [comment]
We are actively working on fixing this now.
